name: update flake.lock

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nix-flake-update:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update flake.lock
        run: |
          nix flake update
          [[ $(git diff flake.lock) != "" ]] || exit 0
          git config --local user.name "Hacl Bot"
          git config --local user.email "hacl-star@mailo.com"
          git add flake.lock
          git commit -m "[CI] update flake.lock"
          nix build .#hacl
      - name: push
        uses: ad-m/github-push-action@master
        with:
          branch: main
